### ISSUE TITLE
Change textual representation of alias

### ISSUE THREAD

**Issue by shilch** [lane-c-wagner/ccap#1]
The current document defines the textual representation of an alias as `@user.domain` to avoid confusion with email addresses. However, this has the drawback that a username can not contain a dot. Furthermore, the @-char is associated with messaging and not with cash.  
I propose changing the representation to `user$domain`. This solves the previously named issues. Also, the $-char is available on every keyboard as well.  
I would be happy to help implementing the (modified) protocol!

**Comment by lane-c-wagner** [comment]
Let's have a discussion around this. One one hand, people have claimed lane$ogdolo.com doesn't look pretty (which is important because thats the point of an alias in the first place). As @shilch pointed out however, no dots are allow in usernames with the @lane.ogdolo.com alias format.

**Comment by shilch** [comment]
I'm not sure what people don't like about the lane$ogdolo.com representation in terms of looks. 

Handcash is using the system `$username`.
Another option is changing the system to `[domain]$username` where the domain is optional if the request does not leave the own domain. This would be compatible and not much of an issue for Handcash to implement. However, for email users the reversed order might be confusing.

A third option I can think of is `$username@domain`. Two special characters might be too much of an overhead though.

**Comment by lane-c-wagner** [comment]
Yeah, I guess I think that after a bit of use lane$ogdolo.com will look fine as people get used to it. People are currently just used to the @lane.ogdolo.com syntax from programs like slack, discord, and twitter.

**Comment by shilch** [comment]
Fine, what do you thing about `user$domain` vs `[domain]$user`?  
Personally, I would prefer latter because of the optional domain (easy integration with HandCash and some other advantages if we think long-term). However, the first one probably is easier to get used to.

**Comment by lane-c-wagner** [comment]
How could [domain] be optional? Wallet software will need to know which server to access when querying a user. (lane@gmail.com != lane@hotmail.com)

**Comment by shilch** [comment]
An optional domain would be used if you are sending cryptocurrency to an address in the same domain as you.  
Example:  
- an exchange allows withdrawing using a ccap handle. If you leave out the domain, a user can withdraw to another account on the same exchange  
- same would be applicable to cryptocurrency banks  

There are probably much more use-cases where shorter handles come handy.

**Comment by lane-c-wagner** [comment]
Absolutely, that would just be a client specific implementation. The
protocol would still need to include servers.

**Comment by shilch** [comment]
Oh, yeah. You're right about that. This is client side and not protocol specific. That still needs us to decide on the representation: `user$[domain]` or `[domain]$user`.  
The first looks better when we have a domain and the second when we don't have a domain (see handcash handles).  
We could as well use `user$domain` and `$user` if we don't have a domain but that's probably confusing and not very consequent.

**Comment by lane-c-wagner** [comment]
The first definitely looks better I think. I like this conversation, I think we need to get more people involved and maybe do a poll

**Comment by danhalliday** [comment]
I could be missing something, but what’s the argument against using the same format as email addresses?

At present email addresses are used as primary identifiers for many services hosted at a domain (eg. an email provider offering shareable calendars, shared by means of the users bame@domain identifier).

For the average non-technical user, wouldn’t they want to have a crypto currency alias that’s the same as their email address? (Assuming their email provider would offer that service, which seems likely eventually) I know many people who have trouble managing just a couple of email addresses say for family and work, and I think they would be really confused if they ended up with something like user@domain.com and user$domain.com for money, remembering what the difference is.

Isn’t this a great chance to reuse an existing standard?

**Comment by shilch** [comment]
Just using the email format is an option as well that I would support.
Then the question comes up whether we want to integrate CCAP into existing SMTP (maybe there is a way of doing so?) or create an own protocol. Personally, I would tend to latter.

Am 21. Juli 2018 21:57:34 MESZ schrieb Dan Halliday <notifications@github.com>:

**Comment by ThatBrianDude** [comment]
Sending funds to email adresses is already a reality with PayPal so thats an easy YES from me as well.

**Comment by cryptocode** [comment]
At this point you start wondering about if the alias service is really a vCard service. A vCard owner would have to confirm each entry (email verification for email, SMS for phone numbers, etc), but the possibilities are endless, like being able to send to anyone in the phone contact list with a matching entry.

**Comment by lane-c-wagner** [comment]
My only argument would be people confusing emails with addresses and vice versa. For instance I have an alias that I happen to not have an email for, or an email that isn't my alias. I think it holds some water but I'm not sure how much. I created a survey: Upvote this on reddit and take the survey, I'll publish the results.

https://www.reddit.com/r/CryptoCurrency/comments/90swnp/crytpo_poll_time_we_want_public_input_for_this/

**Comment by ThatBrianDude** [comment]
I don't think two way confusion is an issue as any proper client should let you know that the recipient address does not exist. (email as well as ccap)

Also, I can think of almost no situation in which I wouldn't have been explicitly told to either "contact" or "pay" the given address. 

Say you noted an address for future reference, the first thing anyone would do is assume its an email in which case the client will tell them its not. 

Additionally, PayPal kind of already proved that there are no issues in people thinking that exclusive email addresses are also registered at PayPal and even if, again, the client will let them know its not.

**Comment by lane-c-wagner** [comment]
I'm gonna play devils advocate for one last point:
What If someone has the email mike@yahoo.com, then yahoo decides to host a CCAP server. Now another mike comes along and makes the alias make@yahoo.com? Could that cause potential issues?

**Comment by danhalliday** [comment]
Wouldn’t creation of alias@domain.com be under the control of the owner of domain.com? As far as I can see that wouldn’t be a problem because domain.com wouldn’t allow a second user to take an existing address, same as with email (or any username)

**Comment by lane-c-wagner** [comment]
@danhalliday agreed. I'm coming onboard to the email idea I think.

**Comment by shilch** [comment]
Great that we've come to an conclusion!  
I'm closing this issue for now. If there are more opinions on this topic, you're free to comment.

**Comment by lane-c-wagner** [comment]
Anyone want to submit a PR with the changes?

**Comment by shilch** [comment]
Working on it right now
